### ISSUE TITLE
will not connect

### ISSUE THREAD

**Issue by medoix** [azoff/juicebot#9]
What could be the issue for the bellow? I have been using the same credentials for other bots i have been testing and it works great, but with juicebot it just wont connect.

<pre>
> Connecting to server...

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:646:11)
    at Object.afterConnect [as oncomplete] (net.js:637:18)
</pre>

**Comment by azoff** [comment]
@medoix Not sure what's going on here. Is that the full stack trace?
